version: "3.8"
services:
  backend:
    hostname: ${PROJECT_NAME}_backend
    container_name: ws-backend-devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 80:8080
    tty: true
